metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.modules:
  - module: prometheus
    period: 10s
    hosts: ["192.168.253.178:9090"]
    metrics_path: /metrics
    metrics_filter:
      include: ["*"]

setup.dashboard.enable: true

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: 'elasticsearch:9200'
  username: 'elastic'
  password: 'changeme'

setup.kibana:
  host: "192.168.253.178:5601"
  username: "elastic"  
  password: "changeme"
